{"name": "test_query_results_cannot_be_retrieved[Empty key]", "status": "passed", "description": "\n        As a user\n        When I retrieve query results incorrect data\n        Then I get an error response\n        ", "attachments": [{"name": "log", "source": "9acf5985-118a-41d0-9bea-9e92a2801665-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "6cf30ae6-0670-465d-bffd-56695cd7d7a1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "key", "value": "' '"}, {"name": "expected_error", "value": "<harness.api.model.error.api_error.ApiError object at 0x10ee745e0>"}], "start": 1698654754992, "stop": 1698654755039, "uuid": "e2cbfdb0-e186-41be-bfd2-2f26d8050705", "historyId": "004cbe78de003bb674c327227be0cb8b", "testCaseId": "120e73d2e377017af9b514a4ef7282bf", "fullName": "tests.integration.api.consume.powerbi.test_get_query_results.TestApiGetQueryResults#test_query_results_cannot_be_retrieved", "labels": [{"name": "story", "value": "Query results cannot be retrieved"}, {"name": "parentSuite", "value": "[API] ConsumeQuery"}, {"name": "feature", "value": "Get query results"}, {"name": "tag", "value": "@pytest.mark.usefixtures('authenticate_neos_admin')"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "consume"}, {"name": "suite", "value": "test_get_query_results"}, {"name": "subSuite", "value": "TestApiGetQueryResults"}, {"name": "host", "value": "Is-MacBook-Pro.local"}, {"name": "thread", "value": "26201-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.api.consume.powerbi.test_get_query_results"}]}