{"name": "test_query_results_cannot_be_retrieved_when_action_denied_for_group", "status": "skipped", "statusDetails": {"message": "XFAIL Bug https://neom.atlassian.net/browse/NEOS-3266 [BE] 500 error when user without product:consume permissions tries to list products or run statement (GET powerbi/products, POST powerbi/statement)\n\nrequests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://ivanh2.neosdata.cloud/api/iam/group/UNDEFINED/principals", "trace": "../../../Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/pytest_lazyfixture.py:39: in fill\n    _fillfixtures()\ntests/integration/api/iam/group/conftest.py:70: in add_principal\n    group.add_principals_to_group(principals=PrincipalsData(principals=[new_user_data.uuid]))\nharness/helpers/api/hub/iam/group.py:97: in add_principals_to_group\n    response.raise_for_status()\n../../../Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/requests/models.py:1021: in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nE   requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://ivanh2.neosdata.cloud/api/iam/group/UNDEFINED/principals"}, "description": "\n        As a user\n        When I have `product:consume` action denied for a group that user belongs to (for gateway and registry)\n        And I retrieve query results\n        Then I get an error response\n        ", "attachments": [{"name": "log", "source": "92973bf9-e5c2-4f6c-92c2-469e0dca37f0-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "07a8dbcc-445e-4602-985e-8fba22380382-attachment.txt", "type": "text/plain"}], "start": 1698654786109, "stop": 1698654786109, "uuid": "8ce7e886-f377-4666-9b5c-756843c38c6d", "historyId": "e80470a1a97bb90c110402d1668bf71a", "testCaseId": "e80470a1a97bb90c110402d1668bf71a", "fullName": "tests.integration.api.consume.powerbi.test_get_query_results.TestApiGetQueryResults#test_query_results_cannot_be_retrieved_when_action_denied_for_group", "labels": [{"name": "feature", "value": "Get query results"}, {"name": "story", "value": "Query results cannot be retrieved when `product:consume` action denied for group for gateway and registry"}, {"name": "parentSuite", "value": "[API] ConsumeQuery"}, {"name": "tag", "value": "@pytest.mark.usefixtures('authenticate_neos_admin', 'create_product_1_v2', 'add_product_1_schema_v2', 'add_rows_to_product_1_table', 'create_data_product_v2', 'add_schema_v2', 'builder_set_product_1_as_input', 'builder_run', 'publish_data_product_v2', 'create_user', 'add_principal', 'set_group_policy_type', 'deny_product_consume_action', 'deny_registry_product_consume_action', 'create_group_policy', 'authenticate_as_new_user', 'run_select_query')"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Bug https://neom.atlassian.net/browse/NEOS-3266 [BE] 500 error when user without product:consume permissions tries to list products or run statement (GET powerbi/products, POST powerbi/statement)')"}, {"name": "tag", "value": "access"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "consume"}, {"name": "suite", "value": "test_get_query_results"}, {"name": "subSuite", "value": "TestApiGetQueryResults"}, {"name": "host", "value": "Is-MacBook-Pro.local"}, {"name": "thread", "value": "26202-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.api.consume.powerbi.test_get_query_results"}]}