{"name": "test_query_cannot_be_run[Table name starting with a dot]", "status": "skipped", "statusDetails": {"message": "XFAIL Bug https://neom.atlassian.net/browse/NEOS-3253 [BE] 500 error when selecting not published or just not existing table (POST powerbi/statement)\n\nAssertionError: Server error 500 {\"code\":\"0x0060016\",\"message\":\"could not get table - identifier mapping\"}\n is returned", "trace": "tests/integration/api/consume/powerbi/test_run_query.py:178: in test_query_cannot_be_run\n    assert ApiError.from_response(response) == expected_error\nharness/api/model/error/api_error.py:82: in from_response\n    assert response.status_code < 500, f\"Server error {response.status_code} {response.text} is returned\"\nE   AssertionError: Server error 500 {\"code\":\"0x0060016\",\"message\":\"could not get table - identifier mapping\"}\nE    is returned"}, "description": "\n        As a user\n        When I run query with incorrect data\n        Then I get an error response\n        ", "attachments": [{"name": "log", "source": "461fd3b8-e7a5-44a0-973f-bc9f1c8beffb-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d08faf32-8e37-4eab-9462-633f4afd2cad-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "query_data", "value": "QueryData(query='SELECT * FROM .postgres.neos.test_table')"}, {"name": "expected_error", "value": "<harness.api.model.error.api_error.ApiError object at 0x10f41c400>"}], "start": 1698654814118, "stop": 1698654814174, "uuid": "03f08ab3-82f3-4098-989f-d017e0db3079", "historyId": "222a20c5759e312ec34a5a813e6d3bfc", "testCaseId": "4b2dc8dbeda1194c185f4356f562de89", "fullName": "tests.integration.api.consume.powerbi.test_run_query.TestApiRunQuery#test_query_cannot_be_run", "labels": [{"name": "story", "value": "Query cannot be run"}, {"name": "feature", "value": "Run query"}, {"name": "parentSuite", "value": "[API] ConsumeQuery"}, {"name": "tag", "value": "@pytest.mark.usefixtures('authenticate_neos_admin')"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Bug https://neom.atlassian.net/browse/NEOS-3253 [BE] 500 error when selecting not published or just not existing table (POST powerbi/statement)')"}, {"name": "tag", "value": "consume"}, {"name": "suite", "value": "test_run_query"}, {"name": "subSuite", "value": "TestApiRunQuery"}, {"name": "host", "value": "Is-MacBook-Pro.local"}, {"name": "thread", "value": "26202-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.api.consume.powerbi.test_run_query"}]}